import {defineField, defineType} from 'sanity'
import {createAutoSlugDocumentInput} from './components/AutoSlugInput'

export const verhuurVoertuig = defineType({
  name: 'verhuurVoertuig',
  title: 'Te huur — motorhome',
  type: 'document',
  components: {
    input: createAutoSlugDocumentInput({bronVeld: 'titel', documentType: 'verhuurVoertuig'}),
  },
  groups: [
    {name: 'algemeen', title: 'Algemeen', default: true},
    {name: 'specificaties', title: 'Specificaties'},
    {name: 'tarieven', title: 'Tarieven'},
    {name: 'uitrusting', title: 'Uitrusting & accessoires'},
    {name: 'media', title: "Foto's"},
  ],
  fieldsets: [
    {name: 'afmetingenSet', title: 'Afmetingen (m)', options: {columns: 3}},
    {name: 'mindervalidenSet', title: 'Mindervaliden'},
    {name: 'plaatsenSet', title: 'Plaatsen', options: {columns: 2}},
    {name: 'technischSet', title: 'Technische gegevens', options: {columns: 2}},
    {name: 'gewichtSet', title: 'Gewicht', options: {columns: 2}},
  ],
  fields: [
    defineField({
      name: 'titel',
      title: 'Titel',
      type: 'string',
      description: 'Bv. "Blucamp 527". Dit is ook de grote titel (H1) op de detailpagina. De webadres-link (slug) wordt hier automatisch uit aangemaakt — daar hoef je niets voor te doen.',
      group: 'algemeen',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      hidden: true,
      options: {source: 'titel', maxLength: 96},
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'promoTekst',
      title: 'Promotekst (NL/FR, optioneel)',
      type: 'internationalizedArrayString',
      description: 'Korte actietekst die als label verschijnt op de kaart en de detailpagina, bv. "Gratis wasbeurt" of "Weekendactie". Vul in per taal — laat een taal leeg als er geen actie loopt.',
      group: 'algemeen',
    }),
    defineField({
      name: 'merk',
      title: 'Merk',
      type: 'reference',
      to: [{type: 'merk'}],
      description:
        'Kies het merk uit de lijst. Staat het merk er nog niet bij? Typ de naam en klik op "Nieuwe [merk] aanmaken" — dat merk staat dan meteen klaar voor de volgende camper. Wordt ook gebruikt als filter op de pagina "Te huur".',
      group: 'algemeen',
    }),
    defineField({
      name: 'opbouwtype',
      title: 'Opbouwtype',
      type: 'string',
      description: 'Het type opbouw van de camper. Optioneel: laat leeg als je dit niet wil tonen.',
      options: {list: ['Alkoof', 'Campervan', 'Halfintegraal', 'Integraal'], layout: 'radio'},
      group: 'specificaties',
    }),
    defineField({
      name: 'staat',
      title: 'Staat',
      type: 'string',
      description: 'Is dit een nieuwe camper of een occasie (tweedehands)? Optioneel: laat leeg als je dit niet wil tonen.',
      options: {list: ['Nieuw', 'Occasie'], layout: 'radio'},
      group: 'specificaties',
    }),
    defineField({
      name: 'zitplaatsen',
      title: 'Zitplaatsen',
      type: 'number',
      description: 'Aantal zitplaatsen tijdens het rijden.',
      fieldset: 'plaatsenSet',
      group: 'specificaties',
      validation: (Rule) => Rule.integer().positive(),
    }),
    defineField({
      name: 'slaapplaatsen',
      title: 'Slaapplaatsen',
      type: 'number',
      description: 'Aantal slaapplaatsen. Leeg laten toont "Slaapplaatsen op aanvraag".',
      fieldset: 'plaatsenSet',
      group: 'specificaties',
      validation: (Rule) => Rule.integer().positive(),
    }),
    defineField({
      name: 'onderstel',
      title: 'Onderstel',
      type: 'string',
      description: 'Merk en type van het chassis, bv. "Ford Transit".',
      fieldset: 'technischSet',
      group: 'specificaties',
    }),
    defineField({
      name: 'motor',
      title: 'Motor',
      type: 'string',
      description: 'Bv. "Diesel, 170 pk".',
      fieldset: 'technischSet',
      group: 'specificaties',
    }),
    defineField({
      name: 'brandstof',
      title: 'Brandstof',
      type: 'string',
      description: 'Type brandstof.',
      options: {list: ['Diesel', 'Benzine', 'Elektrisch', 'Hybride']},
      fieldset: 'technischSet',
      group: 'specificaties',
    }),
    defineField({
      name: 'transmissie',
      title: 'Transmissie',
      type: 'string',
      description: 'Type versnellingsbak.',
      options: {list: ['Manueel (handgeschakeld)', 'Automaat']},
      fieldset: 'technischSet',
      group: 'specificaties',
    }),
    defineField({
      name: 'rijbewijs',
      title: 'Rijbewijs',
      type: 'string',
      description: 'Rijbewijs dat nodig is om deze camper te besturen. Meestal "Rijbewijs B".',
      initialValue: 'Rijbewijs B',
      fieldset: 'technischSet',
      group: 'specificaties',
    }),
    defineField({
      name: 'indeling',
      title: 'Indeling (NL/FR)',
      type: 'internationalizedArrayString',
      description: 'Bv. "Tweelingbedden achteraan (2+1) · paviljoenbed vooraan (2)". Vul in per taal — leeg laten toont "Indeling op aanvraag".',
      fieldset: 'technischSet',
      group: 'specificaties',
    }),
    defineField({
      name: 'afmetingen',
      title: 'Afmetingen',
      type: 'object',
      description: 'Lengte, breedte en hoogte in meter. Leeg laten toont "Afmetingen op aanvraag".',
      group: 'specificaties',
      fieldset: 'afmetingenSet',
      fields: [
        defineField({name: 'lengte', title: 'Lengte (m)', type: 'number', description: 'Bv. 7 voor 7 meter.'}),
        defineField({name: 'breedte', title: 'Breedte (m)', type: 'number', description: 'Bv. 2.35.'}),
        defineField({name: 'hoogte', title: 'Hoogte (m)', type: 'number', description: 'Bv. 2.98.'}),
      ],
    }),
    defineField({
      name: 'leeggewicht',
      title: 'Leeggewicht (kg)',
      type: 'number',
      description: 'Gewicht van de camper leeg, in kg. Typ enkel het getal, bv. 2500 voor 2.500 kg.',
      fieldset: 'gewichtSet',
      group: 'specificaties',
      validation: (Rule) => Rule.positive(),
    }),
    defineField({
      name: 'mtm',
      title: 'MTM (kg)',
      type: 'number',
      description: 'Maximaal toegelaten massa, in kg. Typ enkel het getal, bv. 3500 voor 3.500 kg.',
      fieldset: 'gewichtSet',
      group: 'specificaties',
      validation: (Rule) => Rule.positive(),
    }),
    defineField({
      name: 'mindervalideGeschikt',
      title: 'Geschikt voor mindervaliden',
      type: 'boolean',
      description: 'Zet aan als deze camper is aangepast voor personen met een beperkte mobiliteit.',
      initialValue: false,
      fieldset: 'mindervalidenSet',
      group: 'specificaties',
    }),
    defineField({
      name: 'mindervalideAanpassingen',
      title: 'Aanpassingen voor mindervaliden',
      type: 'array',
      of: [{type: 'string'}],
      description: 'Som op welke aanpassingen deze camper heeft. Eén aanpassing per regel, bv. "Stuurbediening", "Bredere deur", "Lift voor rolstoel".',
      fieldset: 'mindervalidenSet',
      group: 'specificaties',
      hidden: ({parent}) => !parent?.mindervalideGeschikt,
    }),
    defineField({
      name: 'coverFoto',
      title: 'Kaartfoto',
      type: 'image',
      description: 'Deze ene foto verschijnt op de overzichtskaartjes (bv. op de pagina "Te huur"). Kies een duidelijke foto van de buitenkant, het liefst liggend (breed) formaat.',
      options: {hotspot: true},
      group: 'media',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'fotos',
      title: "Fotogalerij",
      type: 'array',
      group: 'media',
      description: "Alle foto's voor de fotogalerij op de detailpagina van deze camper. Voeg de kaartfoto hierboven hier gerust nog eens toe als die ook als eerste foto in de galerij moet staan. Versleep de foto's om de volgorde te wijzigen.",
      of: [
        {
          type: 'image',
          options: {hotspot: true},
          fields: [{name: 'alt', title: 'Alt-tekst', type: 'string', description: 'Korte omschrijving van de foto, voor schermlezers en zoekmachines.'}],
        },
      ],
      validation: (Rule) => Rule.min(1).error('Voeg minstens één foto toe aan de galerij.'),
    }),
    defineField({
      name: 'dagindeling',
      title: 'Foto dagindeling',
      type: 'image',
      description: 'Optioneel: foto van het grondplan / de indeling overdag (bv. de zitruimte).',
      options: {hotspot: true},
      group: 'media',
    }),
    defineField({
      name: 'nachtindeling',
      title: 'Foto nachtindeling',
      type: 'image',
      description: 'Optioneel: foto van het grondplan / de indeling \'s nachts (bv. de bedden).',
      options: {hotspot: true},
      group: 'media',
    }),
    defineField({
      name: 'tarieven',
      title: 'Huurtarieven',
      type: 'object',
      group: 'tarieven',
      description: 'Alle bedragen incl. 21 % btw. Typ enkel het getal, zonder punten, komma of €-teken (bv. 900 voor € 900,00). Leeg laten toont "Prijs op aanvraag".',
      fields: [
        defineField({name: 'laagSeizoen', title: 'Laag seizoen (01/11 – 30/04)', type: 'tariefPeriode'}),
        defineField({name: 'middenSeizoen', title: 'Midden seizoen (krokus, Pasen, Hemelvaart, Kerst, 01/05 – 30/06 en 01/09 – 31/10)', type: 'tariefPeriode'}),
        defineField({name: 'hoogSeizoen', title: 'Hoogseizoen (01/07 – 31/08)', type: 'tariefPeriode'}),
      ],
    }),
    defineField({
      name: 'chassisEnCabine',
      title: 'Chassis & cabine (NL/FR)',
      type: 'internationalizedArrayText',
      group: 'uitrusting',
      description: 'Eén kenmerk per regel, bv.\nAirco\nCruisecontrol\nABS / ESP / EBD\nElk kenmerk verschijnt als apart vinkje in de kolom "Chassis & cabine" op de website. Vul in per taal — laat een taal leeg om deze kolom niet te tonen.',
    }),
    defineField({
      name: 'woongedeelte',
      title: 'Woongedeelte (NL/FR)',
      type: 'internationalizedArrayText',
      group: 'uitrusting',
      description: 'Eén kenmerk per regel, bv.\nKoelkast 84 L\nTruma verwarming\nPanoramisch dakraam\nElk kenmerk verschijnt als apart vinkje in de kolom "Woongedeelte" op de website. Vul in per taal — laat een taal leeg om deze kolom niet te tonen.',
    }),
    defineField({
      name: 'extras',
      title: "Extra's (NL/FR)",
      type: 'internationalizedArrayText',
      group: 'uitrusting',
      description: 'Eén kenmerk per regel, bv.\nZonnepaneel\nFietsendrager\nAchteruitrijcamera\nElk kenmerk verschijnt als apart vinkje in de kolom "Extra\'s" op de website. Vul in per taal — laat een taal leeg om deze kolom niet te tonen.',
    }),
    defineField({
      name: 'notitie',
      title: 'Extra notitie (NL/FR, optioneel)',
      type: 'internationalizedArrayText',
      group: 'algemeen',
      description: 'Bv. uitzonderingen op de standaard huurvoorwaarden voor dit voertuig. Vul in per taal.',
    }),
    defineField({
      name: 'gepubliceerd',
      title: 'Gepubliceerd',
      type: 'boolean',
      description: 'Zet uit om deze camper tijdelijk van de website te halen zonder hem te verwijderen.',
      initialValue: true,
      group: 'algemeen',
    }),
    defineField({
      name: 'volgorde',
      title: 'Sorteervolgorde',
      type: 'number',
      description: 'Lager getal staat hoger op het overzicht. Leeg = onderaan, op titel gesorteerd.',
      group: 'algemeen',
    }),
  ],
  orderings: [{title: 'Sorteervolgorde', name: 'volgordeAsc', by: [{field: 'volgorde', direction: 'asc'}]}],
  preview: {
    select: {title: 'titel', slaapplaatsen: 'slaapplaatsen', media: 'coverFoto'},
    prepare({title, slaapplaatsen, media}) {
      return {
        title,
        subtitle: slaapplaatsen ? `${slaapplaatsen} slaapplaatsen` : 'Slaapplaatsen op aanvraag',
        media,
      }
    },
  },
})
