import {defineField, defineType} from 'sanity'
import {createAutoSlugDocumentInput} from './components/AutoSlugInput'

export const verkoopVoertuig = defineType({
  name: 'verkoopVoertuig',
  title: 'Te koop — motorhome',
  type: 'document',
  components: {
    input: createAutoSlugDocumentInput({bronVeld: 'titel', documentType: 'verkoopVoertuig'}),
  },
  groups: [
    {name: 'algemeen', title: 'Algemeen', default: true},
    {name: 'specificaties', title: 'Specificaties'},
    {name: 'uitrusting', title: 'Uitrusting & accessoires'},
    {name: 'media', title: "Foto's"},
  ],
  fieldsets: [
    {
      name: 'promoSet',
      title: 'Promo (optioneel)',
      options: {columns: 2, collapsible: true, collapsed: true},
    },
    {name: 'plaatsenSet', title: 'Plaatsen', options: {columns: 2}},
    {name: 'identificatieSet', title: 'Identificatie', options: {columns: 3}},
    {name: 'technischSet', title: 'Technische gegevens', options: {columns: 2}},
    {name: 'gewichtSet', title: 'Gewicht', options: {columns: 2}},
    {name: 'mindervalidenSet', title: 'Mindervaliden'},
  ],
  fields: [
    defineField({
      name: 'titel',
      title: 'Titel',
      type: 'string',
      description: 'Merk + model, bv. "Benimar Cocoon 486". Dit is ook de grote titel (H1) op de detailpagina. De webadres-link (slug) wordt hier automatisch uit aangemaakt — daar hoef je niets voor te doen.',
      group: 'algemeen',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      hidden: true,
      options: {source: 'titel', maxLength: 96},
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'merk',
      title: 'Merk',
      type: 'reference',
      to: [{type: 'merk'}],
      description:
        'Kies het merk uit de lijst. Staat het merk er nog niet bij? Typ de naam en klik op "Nieuwe [merk] aanmaken" — dat merk staat dan meteen klaar voor de volgende camper.',
      group: 'algemeen',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'groep',
      title: 'Groep (optioneel)',
      type: 'string',
      description: 'Naam van de fabrieksgroep, bv. "LAIKA – Hymer Group". Verschijnt in kleine letters onder de titel op de kaart. Laat leeg als dit niet van toepassing is.',
      group: 'algemeen',
    }),
    defineField({
      name: 'opbouwtype',
      title: 'Opbouwtype',
      type: 'string',
      description: 'Het type opbouw van de camper.',
      options: {list: ['Alkoof', 'Campervan', 'Halfintegraal', 'Integraal'], layout: 'radio'},
      group: 'algemeen',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'staat',
      title: 'Staat',
      type: 'string',
      description: 'Is dit een nieuwe camper of een occasie (tweedehands)?',
      options: {list: ['Nieuw', 'Occasie'], layout: 'radio'},
      group: 'algemeen',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'prijs',
      title: 'Prijs (incl. 21 % btw)',
      type: 'number',
      description: 'Typ enkel het getal, zonder punten, komma of €-teken. Bv. typ 44950 voor € 44.950,00 — de website toont dit automatisch correct opgemaakt.',
      group: 'algemeen',
      validation: (Rule) => Rule.required().positive(),
    }),
    defineField({
      name: 'promoTekst',
      title: 'Promotekst (NL/FR)',
      type: 'internationalizedArrayString',
      description: 'Korte actietekst die als label verschijnt op de kaart en de detailpagina, bv. "Gratis airco" of "Winteractie". Vul in per taal — laat een taal leeg als er geen actie loopt.',
      fieldset: 'promoSet',
      group: 'algemeen',
    }),
    defineField({
      name: 'promoPrijs',
      title: 'Promoprijs',
      type: 'number',
      description: 'Vul dit ENKEL in bij een prijskorting: typ de nieuwe, lagere prijs (zelfde format als het veld "Prijs" hierboven, dus enkel het getal). De gewone prijs wordt dan automatisch doorstreept getoond, met deze promoprijs ernaast als actieprijs.',
      fieldset: 'promoSet',
      group: 'algemeen',
      validation: (Rule) =>
        Rule.positive().custom((waarde, context) => {
          if (waarde === undefined) return true
          const prijs = (context.parent as {prijs?: number} | undefined)?.prijs
          if (prijs !== undefined && waarde >= prijs) {
            return 'De promoprijs moet lager zijn dan de gewone prijs.'
          }
          return true
        }),
    }),
    defineField({
      name: 'zitplaatsen',
      title: 'Zitplaatsen',
      type: 'number',
      description: 'Aantal zitplaatsen tijdens het rijden.',
      fieldset: 'plaatsenSet',
      group: 'algemeen',
      validation: (Rule) => Rule.required().integer().positive(),
    }),
    defineField({
      name: 'slaapplaatsen',
      title: 'Slaapplaatsen',
      type: 'number',
      description: 'Aantal slaapplaatsen.',
      fieldset: 'plaatsenSet',
      group: 'algemeen',
      validation: (Rule) => Rule.required().integer().positive(),
    }),
    defineField({
      name: 'bouwjaar',
      title: 'Bouwjaar',
      type: 'number',
      description: 'Bouwjaar van de camper, bv. 2017.',
      fieldset: 'identificatieSet',
      group: 'specificaties',
      validation: (Rule) => Rule.required().integer().min(1990).max(2100),
    }),
    defineField({
      name: 'eersteInschrijving',
      title: 'Eerste inschrijving',
      type: 'string',
      description: 'Formaat MM/JJJJ, bv. 05/2017.',
      fieldset: 'identificatieSet',
      group: 'specificaties',
    }),
    defineField({
      name: 'kilometerstand',
      title: 'Kilometerstand (km)',
      type: 'number',
      description: 'Typ enkel het getal, zonder punten. Bv. typ 82000 voor 82.000 km.',
      fieldset: 'identificatieSet',
      group: 'specificaties',
      validation: (Rule) => Rule.required().min(0),
    }),
    defineField({
      name: 'motor',
      title: 'Motor',
      type: 'string',
      description: 'Bv. "Diesel, 170 pk".',
      fieldset: 'technischSet',
      group: 'specificaties',
    }),
    defineField({
      name: 'brandstof',
      title: 'Brandstof',
      type: 'string',
      description: 'Type brandstof.',
      options: {list: ['Diesel', 'Benzine', 'Elektrisch', 'Hybride']},
      fieldset: 'technischSet',
      group: 'specificaties',
    }),
    defineField({
      name: 'transmissie',
      title: 'Transmissie',
      type: 'string',
      description: 'Type versnellingsbak.',
      options: {list: ['Manueel (handgeschakeld)', 'Automaat']},
      fieldset: 'technischSet',
      group: 'specificaties',
    }),
    defineField({
      name: 'rijbewijs',
      title: 'Rijbewijs',
      type: 'string',
      description: 'Rijbewijs dat nodig is om deze camper te besturen. Meestal "Type B".',
      initialValue: 'Type B',
      fieldset: 'technischSet',
      group: 'specificaties',
    }),
    defineField({
      name: 'onderstel',
      title: 'Onderstel',
      type: 'string',
      description: 'Merk en type van het chassis, bv. "Ford Transit".',
      fieldset: 'technischSet',
      group: 'specificaties',
    }),
    defineField({
      name: 'indeling',
      title: 'Indeling (NL/FR)',
      type: 'internationalizedArrayString',
      description: 'Korte omschrijving van de indeling, bv. "Geen bed achteraan". Vul in per taal.',
      fieldset: 'technischSet',
      group: 'specificaties',
    }),
    defineField({
      name: 'leeggewicht',
      title: 'Leeggewicht (kg)',
      type: 'number',
      description: 'Gewicht van de camper leeg, in kg. Typ enkel het getal, bv. 2500 voor 2.500 kg.',
      fieldset: 'gewichtSet',
      group: 'specificaties',
      validation: (Rule) => Rule.positive(),
    }),
    defineField({
      name: 'mtm',
      title: 'MTM (kg)',
      type: 'number',
      description: 'Maximaal toegelaten massa, in kg. Typ enkel het getal, bv. 3500 voor 3.500 kg.',
      fieldset: 'gewichtSet',
      group: 'specificaties',
      validation: (Rule) => Rule.positive(),
    }),
    defineField({
      name: 'garantie',
      title: 'Garantie (NL/FR)',
      type: 'internationalizedArrayText',
      description: 'Bv. "Ford-fabrieksgarantie tot 5 jaar / 100.000 km". Vul in per taal — laat een taal leeg als er geen (extra) garantie is.',
      group: 'specificaties',
    }),
    defineField({
      name: 'mindervalideGeschikt',
      title: 'Geschikt voor mindervaliden',
      type: 'boolean',
      description: 'Zet aan als deze camper is aangepast voor personen met een beperkte mobiliteit.',
      initialValue: false,
      fieldset: 'mindervalidenSet',
      group: 'specificaties',
    }),
    defineField({
      name: 'mindervalideAanpassingen',
      title: 'Aanpassingen voor mindervaliden',
      type: 'array',
      of: [{type: 'string'}],
      description: 'Som op welke aanpassingen deze camper heeft. Eén aanpassing per regel, bv. "Stuurbediening", "Bredere deur", "Lift voor rolstoel".',
      fieldset: 'mindervalidenSet',
      group: 'specificaties',
      hidden: ({parent}) => !parent?.mindervalideGeschikt,
    }),
    defineField({
      name: 'coverFoto',
      title: 'Kaartfoto',
      type: 'image',
      description: 'Deze ene foto verschijnt op de overzichtskaartjes (bv. op de pagina "Te koop"). Kies een duidelijke foto van de buitenkant, het liefst liggend (breed) formaat.',
      options: {hotspot: true},
      group: 'media',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'fotos',
      title: "Fotogalerij",
      type: 'array',
      group: 'media',
      description: "Alle foto's voor de fotogalerij op de detailpagina van deze camper. Voeg de kaartfoto hierboven hier gerust nog eens toe als die ook als eerste foto in de galerij moet staan. Versleep de foto's om de volgorde te wijzigen.",
      of: [
        {
          type: 'image',
          options: {hotspot: true},
          fields: [{name: 'alt', title: 'Alt-tekst', type: 'string', description: 'Korte omschrijving van de foto, voor schermlezers en zoekmachines.'}],
        },
      ],
      validation: (Rule) => Rule.min(1).error('Voeg minstens één foto toe aan de galerij.'),
    }),
    defineField({
      name: 'dagindeling',
      title: 'Foto dagindeling',
      type: 'image',
      description: 'Optioneel: foto van het grondplan / de indeling overdag (bv. de zitruimte).',
      options: {hotspot: true},
      group: 'media',
    }),
    defineField({
      name: 'nachtindeling',
      title: 'Foto nachtindeling',
      type: 'image',
      description: 'Optioneel: foto van het grondplan / de indeling \'s nachts (bv. de bedden).',
      options: {hotspot: true},
      group: 'media',
    }),
    defineField({
      name: 'chassisEnCabine',
      title: 'Chassis & cabine (NL/FR)',
      type: 'internationalizedArrayText',
      group: 'uitrusting',
      description: 'Eén kenmerk per regel, bv.\nAirco\nCruisecontrol\nABS / ESP / EBD\nElk kenmerk verschijnt als apart vinkje in de kolom "Chassis & cabine" op de website. Vul in per taal — laat een taal leeg om deze kolom niet te tonen.',
    }),
    defineField({
      name: 'woongedeelte',
      title: 'Woongedeelte (NL/FR)',
      type: 'internationalizedArrayText',
      group: 'uitrusting',
      description: 'Eén kenmerk per regel, bv.\nKoelkast 84 L\nTruma verwarming\nPanoramisch dakraam\nElk kenmerk verschijnt als apart vinkje in de kolom "Woongedeelte" op de website. Vul in per taal — laat een taal leeg om deze kolom niet te tonen.',
    }),
    defineField({
      name: 'extras',
      title: "Extra's (NL/FR)",
      type: 'internationalizedArrayText',
      group: 'uitrusting',
      description: 'Eén kenmerk per regel, bv.\nZonnepaneel\nFietsendrager\nAchteruitrijcamera\nElk kenmerk verschijnt als apart vinkje in de kolom "Extra\'s" op de website. Vul in per taal — laat een taal leeg om deze kolom niet te tonen.',
    }),
    defineField({
      name: 'gepubliceerd',
      title: 'Gepubliceerd',
      type: 'boolean',
      description: 'Zet uit om deze camper tijdelijk van de website te halen zonder hem te verwijderen.',
      initialValue: true,
      group: 'algemeen',
    }),
    defineField({
      name: 'volgorde',
      title: 'Sorteervolgorde',
      type: 'number',
      description: 'Lager getal staat hoger op het overzicht. Leeg = onderaan, op titel gesorteerd.',
      group: 'algemeen',
    }),
  ],
  orderings: [
    {title: 'Sorteervolgorde', name: 'volgordeAsc', by: [{field: 'volgorde', direction: 'asc'}]},
    {title: 'Nieuwste eerst', name: 'bouwjaarDesc', by: [{field: 'bouwjaar', direction: 'desc'}]},
  ],
  preview: {
    select: {title: 'titel', staat: 'staat', prijs: 'prijs', promoPrijs: 'promoPrijs', media: 'coverFoto'},
    prepare({title, staat, prijs, promoPrijs, media}) {
      const prijsTekst = promoPrijs ? `€ ${promoPrijs.toLocaleString('nl-BE')} (promo)` : prijs ? `€ ${prijs.toLocaleString('nl-BE')}` : null
      return {
        title,
        subtitle: [staat, prijsTekst].filter(Boolean).join(' · '),
        media,
      }
    },
  },
})
